/**
 * This function handles simple onEdit events and detects if the checkbox on the ORDER FORM or BOOKING PROGRAM page is checked and then checks a hidden checkbox on the BOOKING PROGRAM.
 * An external spreadsheet is watching the hidden checkbox and when the value has changed to true, a script will run that locks this spreadsheet from the user and sends emails to the
 * appropriate recipients. This script also sets the values on the hidden ORDER CONFIRMATION and EXPORT sheets in order to attach those documents to the emails.
 * 
 * @param {Event Object} e : The event object generated by the simple on edit trigger.
 * @author Jarren Ralf
 */
function onEdit(e)
{
  const row = e.range.rowStart;
  const col = e.range.columnStart;

  if (row === e.range.rowEnd && col === e.range.columnEnd) // Single cell
  {
    const sheetName = SpreadsheetApp.getActiveSheet().getSheetName();

    if (col === 1 && ((row === 30 &&  sheetName === 'BOOKING PROGRAM') || 
       (row === 2 && (sheetName === 'ORDER FORM' || sheetName === 'Order Form (Hoochies)' || sheetName === 'Order Form (Golden Bait)' || sheetName === 'Order Form (Clearance)'))))
    {
      const spreadsheet = e.source;
      
      if (e.value != 'TRUE') // False; Uncheck all of the boxes
      {
        const orderConfirmationSheet = spreadsheet.getSheetByName('ORDER CONFIRMATION')
        orderConfirmationSheet.getRange(4, 1, orderConfirmationSheet.getLastRow() - 3, orderConfirmationSheet.getLastColumn()).clearContent()
          .offset(0, 0, 1, 1).setFormula(
          "=getOrderConfirmation('Order Form'!A20:J768,'Order Form (Hoochies)'!A19:J469,'Order Form (Golden Bait)'!A19:J146,'Order Form (Clearance)'!A19:J279)")
        
        spreadsheet.getSheetByName('Export').clearContents().getRange(1, 1, 1, 4).setValues([["H", "='BOOKING PROGRAM'!D12", "='BOOKING PROGRAM'!B4", "MAIL"]])
        spreadsheet.getSheetByName('ORDER FORM').getRange('A2').uncheck()
        spreadsheet.getSheetByName('ORDER FORM (Hoochies)').getRange('A2').uncheck()
        spreadsheet.getSheetByName('ORDER FORM (Golden Bait)').getRange('A2').uncheck()
        spreadsheet.getSheetByName('ORDER FORM (Clearance)').getRange('A2').uncheck()
        spreadsheet.getSheetByName('BOOKING PROGRAM').getRange('A30').uncheck().offset(0, 3).uncheck()

        SpreadsheetApp.getUi().alert('Submission Cancelled.');
      }
      else // True; Begin the process of submitting the order
      {
        const ui = SpreadsheetApp.getUi();
        const sheet = spreadsheet.getSheetByName('BOOKING PROGRAM');
        const bookingValues = sheet.getSheetValues(4, 2, 9, 1); // Contains some values to check if the order is ready for submission

        if (bookingValues[8][0] == 0) // If the total is $0.00, then no items have been ordered, therefore prompt the user to order atleast 1 item
        {
          ui.alert('Please order at least 1 item before submitting your booking.')
          e.range.uncheck(); // Uncheck the checkbox that the user selected which triggered this script to run
        }
        else if (bookingValues[0][0] === "Please enter your PO Number here" || bookingValues[0][0] === '') // The customer has not edited the PO field or set it to blank
        {
          ui.alert('Please enter a PO Number before submitting your order.')
          e.range.uncheck(); // Uncheck the checkbox that the user selected which triggered this script to run
          sheet.getRange(4, 2).activate() // Take the user to the PO Number field
        }
        else // Order is ready for submission
        {
          const response = ui.alert('Is your order complete and ready for submission to Pacific Net & Twine?', ui.ButtonSet.YES_NO) // Double check if the user is ready to submit their order

          if (response !== ui.Button.YES) // The user has selected CLOSE or NO
            e.range.uncheck(); // Uncheck the checkbox that the user selected which triggered this script to run
          else
          {
            const orderForm = spreadsheet.getSheetByName('ORDER FORM')
            const orderForm_Hoochies = spreadsheet.getSheetByName('ORDER FORM (Hoochies)')
            const orderForm_GoldenBait = spreadsheet.getSheetByName('ORDER FORM (Golden Bait)')
            const orderForm_Clearance = spreadsheet.getSheetByName('ORDER FORM (Clearance)')
            var orderComfirmData = [], isOrdered;
            orderForm           .getRange('A2').check();
            orderForm_Hoochies  .getRange('A2').check();
            orderForm_GoldenBait.getRange('A2').check();
            orderForm_Clearance .getRange('A2').check();
            spreadsheet.getSheetByName('BOOKING PROGRAM').getRange('A30').check();

            const exportData = [].concat.apply([], [
              orderForm           .getSheetValues(20, 1, orderForm.getLastRow()            - 19, 10),
              orderForm_Hoochies  .getSheetValues(19, 1, orderForm_Hoochies.getLastRow()   - 18, 10),
              orderForm_GoldenBait.getSheetValues(19, 1, orderForm_GoldenBait.getLastRow() - 18, 10),
              orderForm_Clearance .getSheetValues(19, 1, orderForm_Clearance.getLastRow()  - 18, 10)]
            ).filter(item => {
              isOrdered = item[8] !== ''; // Quantity is not blank, therefore this item has been ordered
              
              if (isOrdered)
              {
                orderComfirmData.push([...item])  // Take all values for the order confirmation
                item.unshift('D')                 // The letter 'D' stands for detail line which is required for input into Adagio
                item.pop()                        // Remove the last element in the row because the extended cost is not required in the csv file
                item.splice(2, 6)                 // Remove all non-required elements
                item[2] = Math.round((item[2] + Number.EPSILON) * 100) / 100 // Round to two decimals
              }
              return isOrdered
            });

            spreadsheet.getSheetByName('ORDER CONFIRMATION').getRange(4, 1, orderComfirmData.length, orderComfirmData[0].length).setValues(orderComfirmData)
            spreadsheet.getSheetByName('Export').getRange(2, 1, exportData.length, exportData[0].length).setValues(exportData)
            Utilities.sleep(5000)
            sheet.getRange('D30').check() // This checkbox will trigger the unbound script to lock the sheet and send the appropriate emails
            Utilities.sleep(2000)
            SpreadsheetApp.getUi().alert('Your order has been submitted.\n\nThank You!');
          }
        }
      }
    }
  }
}

/**
 * This function creates the order confirmation that will be email to the customers and sales representatives.
 * 
 * @param {Object[][]} data : The multi array of data that is used to create the order confirmation.
 * @author Jarren Ralf
 * @customfunction
 */
function getOrderConfirmation(data1, data2, data3, data4)
{
  const itemValues = [];
  const orderForm = data1.filter(orderQty => orderQty[8] !== '');
  const orderForm_Hoochies = data2.filter(orderQty => orderQty[8] !== '');
  const orderForm_GoldenBait = data3.filter(orderQty => orderQty[8] !== '');
  const orderForm_Clearance = data4.filter(orderQty => orderQty[8] !== '');

  if (orderForm.length !== 0)
    itemValues.push(...orderForm);
  if (orderForm_Hoochies.length !== 0)
    itemValues.push(...orderForm_Hoochies);
  if (orderForm_GoldenBait.length !== 0)
    itemValues.push(...orderForm_GoldenBait);
  if (orderForm_Clearance.length !== 0)
    itemValues.push(...orderForm_Clearance);
  
  return (itemValues.length === 0) ? '' : itemValues;
}